"""
Property-based tests for Authentication Service

**Validates: Requirements 48.3**

This module tests that JWT tokens generated by the authentication system
can always be successfully verified, ensuring the token generation and
verification process is consistent and reliable.
"""

import pytest
from datetime import datetime, timedelta, timezone
from hypothesis import given, settings, strategies as st
from jose import jwt

from auth_service import (
    create_access_token,
    create_refresh_token,
    verify_token,
    SECRET_KEY,
    ALGORITHM,
)


# ============================================================================
# Hypothesis Strategies
# ============================================================================

@st.composite
def valid_user_data_strategy(draw):
    """
    Generate valid user data for token generation.
    
    Creates diverse user IDs, emails, and names to test token generation
    across a wide range of valid inputs.
    """
    # Generate user ID (UUID-like string)
    user_id = draw(st.uuids()).hex
    
    # Generate email
    username = draw(st.text(
        alphabet=st.characters(whitelist_categories=('L', 'N'), min_codepoint=97, max_codepoint=122),
        min_size=3,
        max_size=20
    ))
    domain = draw(st.sampled_from(['example.com', 'test.org', 'demo.net', 'user.io']))
    email = f"{username}@{domain}"
    
    # Generate name with various character sets
    name = draw(st.text(
        alphabet=st.characters(whitelist_categories=('L', 'Zs')),
        min_size=1,
        max_size=100
    ).filter(lambda x: x.strip() != ''))
    
    return {
        'user_id': user_id,
        'email': email,
        'name': name
    }


# ============================================================================
# Property-Based Tests
# ============================================================================

class TestAuthenticationTokenProperties:
    """
    Property-based tests for JWT token generation and verification.
    
    **Validates: Requirements 48.3**
    """
    
    @given(user_data=valid_user_data_strategy())
    @settings(max_examples=200, deadline=None)
    def test_property_access_token_verification_succeeds(self, user_data):
        """
        Property 3: Token verification succeeds for all valid generated tokens.
        
        **Validates: Requirements 48.3**
        
        For any valid user data (user_id, email, name):
        1. Generate an access token
        2. Verify the token
        3. Assert verification succeeds and returns correct user data
        
        This ensures that all tokens generated by the system can be verified,
        maintaining the integrity of the authentication system.
        """
        user_id = user_data['user_id']
        email = user_data['email']
        name = user_data['name']
        
        # Step 1: Generate access token
        token = create_access_token(user_id, email, name)
        
        # Step 2: Verify the token
        payload = verify_token(token, expected_type="access")
        
        # Step 3: Assert verification succeeds with correct data
        assert payload.sub == user_id, f"User ID mismatch: {payload.sub} != {user_id}"
        assert payload.email == email, f"Email mismatch: {payload.email} != {email}"
        assert payload.name == name, f"Name mismatch: {payload.name} != {name}"
        assert payload.type == "access", f"Token type mismatch: {payload.type} != access"
        
        # Verify token has expiration and issued-at timestamps
        assert payload.exp > 0, "Token expiration not set"
        assert payload.iat > 0, "Token issued-at not set"
        
        # Verify expiration is in the future
        now = datetime.now(timezone.utc).timestamp()
        assert payload.exp > now, "Token is already expired"
    
    @given(user_data=valid_user_data_strategy())
    @settings(max_examples=200, deadline=None)
    def test_property_refresh_token_verification_succeeds(self, user_data):
        """
        Property 3 (Refresh variant): Refresh token verification succeeds for all valid generated tokens.
        
        **Validates: Requirements 48.3**
        
        For any valid user data (user_id, email, name):
        1. Generate a refresh token
        2. Verify the token
        3. Assert verification succeeds and returns correct user data
        
        This ensures that all refresh tokens generated by the system can be verified.
        """
        user_id = user_data['user_id']
        email = user_data['email']
        name = user_data['name']
        
        # Step 1: Generate refresh token
        token = create_refresh_token(user_id, email, name)
        
        # Step 2: Verify the token
        payload = verify_token(token, expected_type="refresh")
        
        # Step 3: Assert verification succeeds with correct data
        assert payload.sub == user_id, f"User ID mismatch: {payload.sub} != {user_id}"
        assert payload.email == email, f"Email mismatch: {payload.email} != {email}"
        assert payload.name == name, f"Name mismatch: {payload.name} != {name}"
        assert payload.type == "refresh", f"Token type mismatch: {payload.type} != refresh"
        
        # Verify token has expiration and issued-at timestamps
        assert payload.exp > 0, "Token expiration not set"
        assert payload.iat > 0, "Token issued-at not set"
        
        # Verify expiration is in the future
        now = datetime.now(timezone.utc).timestamp()
        assert payload.exp > now, "Token is already expired"
    
    @given(user_data=valid_user_data_strategy())
    @settings(max_examples=100, deadline=None)
    def test_property_token_roundtrip_consistency(self, user_data):
        """
        Property: Token generation and verification is consistent (round-trip).
        
        **Validates: Requirements 48.3**
        
        For any valid user data:
        1. Generate a token
        2. Verify the token to extract payload
        3. Generate a new token with the extracted data
        4. Verify both tokens contain the same user information
        
        This ensures consistency in the token generation process.
        """
        user_id = user_data['user_id']
        email = user_data['email']
        name = user_data['name']
        
        # Step 1: Generate first token
        token1 = create_access_token(user_id, email, name)
        
        # Step 2: Verify and extract payload
        payload1 = verify_token(token1, expected_type="access")
        
        # Step 3: Generate second token with extracted data
        token2 = create_access_token(payload1.sub, payload1.email, payload1.name)
        
        # Step 4: Verify second token
        payload2 = verify_token(token2, expected_type="access")
        
        # Assert both payloads contain the same user information
        assert payload1.sub == payload2.sub
        assert payload1.email == payload2.email
        assert payload1.name == payload2.name
        assert payload1.type == payload2.type
    
    @given(user_data=valid_user_data_strategy())
    @settings(max_examples=100, deadline=None)
    def test_property_token_contains_all_required_fields(self, user_data):
        """
        Property: All generated tokens contain required JWT fields.
        
        **Validates: Requirements 48.3**
        
        For any valid user data:
        1. Generate a token
        2. Decode the raw JWT payload
        3. Assert all required fields are present
        
        This ensures tokens are properly structured according to JWT standards.
        """
        user_id = user_data['user_id']
        email = user_data['email']
        name = user_data['name']
        
        # Generate token
        token = create_access_token(user_id, email, name)
        
        # Decode raw JWT payload (without verification for inspection)
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        
        # Assert all required fields are present
        required_fields = ['sub', 'email', 'name', 'exp', 'iat', 'type']
        for field in required_fields:
            assert field in payload, f"Required field '{field}' missing from token payload"
        
        # Assert field values are correct
        assert payload['sub'] == user_id
        assert payload['email'] == email
        assert payload['name'] == name
        assert payload['type'] == 'access'
        assert isinstance(payload['exp'], int)
        assert isinstance(payload['iat'], int)
    
    @given(user_data=valid_user_data_strategy())
    @settings(max_examples=100, deadline=None)
    def test_property_token_expiration_is_in_future(self, user_data):
        """
        Property: All generated tokens have expiration in the future.
        
        **Validates: Requirements 48.3**
        
        For any valid user data:
        1. Generate a token
        2. Extract expiration timestamp
        3. Assert expiration is after current time
        
        This ensures tokens are immediately usable after generation.
        """
        user_id = user_data['user_id']
        email = user_data['email']
        name = user_data['name']
        
        # Capture time before token generation
        before = datetime.now(timezone.utc)
        
        # Generate token
        token = create_access_token(user_id, email, name)
        
        # Capture time after token generation
        after = datetime.now(timezone.utc)
        
        # Verify token
        payload = verify_token(token, expected_type="access")
        
        # Extract expiration
        exp_time = datetime.fromtimestamp(payload.exp, tz=timezone.utc)
        
        # Assert expiration is in the future
        assert exp_time > before, "Token expiration is not in the future"
        assert exp_time > after, "Token expiration is not in the future"
    
    @given(user_data=valid_user_data_strategy())
    @settings(max_examples=50, deadline=None)
    def test_property_access_and_refresh_tokens_are_different(self, user_data):
        """
        Property: Access and refresh tokens for the same user are different.
        
        **Validates: Requirements 48.3**
        
        For any valid user data:
        1. Generate an access token
        2. Generate a refresh token
        3. Assert the tokens are different
        
        This ensures proper token type differentiation.
        """
        user_id = user_data['user_id']
        email = user_data['email']
        name = user_data['name']
        
        # Generate both token types
        access_token = create_access_token(user_id, email, name)
        refresh_token = create_refresh_token(user_id, email, name)
        
        # Assert tokens are different
        assert access_token != refresh_token, "Access and refresh tokens should be different"
        
        # Verify both tokens work with their respective types
        access_payload = verify_token(access_token, expected_type="access")
        refresh_payload = verify_token(refresh_token, expected_type="refresh")
        
        # Assert both contain the same user data
        assert access_payload.sub == refresh_payload.sub
        assert access_payload.email == refresh_payload.email
        assert access_payload.name == refresh_payload.name
        
        # Assert token types are different
        assert access_payload.type == "access"
        assert refresh_payload.type == "refresh"
    
    @given(
        user_data=valid_user_data_strategy(),
        iterations=st.integers(min_value=2, max_value=10)
    )
    @settings(max_examples=50, deadline=None)
    def test_property_multiple_token_generations_all_verify(self, user_data, iterations):
        """
        Property: Multiple tokens generated for the same user all verify successfully.
        
        **Validates: Requirements 48.3**
        
        For any valid user data and number of iterations:
        1. Generate multiple tokens for the same user
        2. Verify all tokens
        3. Assert all verifications succeed
        
        This ensures the token generation process is reliable and repeatable.
        """
        user_id = user_data['user_id']
        email = user_data['email']
        name = user_data['name']
        
        tokens = []
        
        # Generate multiple tokens
        for _ in range(iterations):
            token = create_access_token(user_id, email, name)
            tokens.append(token)
        
        # Verify all tokens
        for token in tokens:
            payload = verify_token(token, expected_type="access")
            
            # Assert each token contains correct user data
            assert payload.sub == user_id
            assert payload.email == email
            assert payload.name == name
            assert payload.type == "access"
    
    @given(user_data=valid_user_data_strategy())
    @settings(max_examples=100, deadline=None)
    def test_property_token_issued_at_is_reasonable(self, user_data):
        """
        Property: Token issued-at timestamp is close to current time.
        
        **Validates: Requirements 48.3**
        
        For any valid user data:
        1. Capture current time
        2. Generate a token
        3. Extract issued-at timestamp
        4. Assert issued-at is within reasonable bounds of current time
        
        This ensures tokens have accurate timestamps.
        """
        user_id = user_data['user_id']
        email = user_data['email']
        name = user_data['name']
        
        # Capture time before and after token generation (as integers to match JWT format)
        before = int(datetime.now(timezone.utc).timestamp())
        token = create_access_token(user_id, email, name)
        after = int(datetime.now(timezone.utc).timestamp())
        
        # Verify token
        payload = verify_token(token, expected_type="access")
        
        # Assert issued-at is within the time window (allow 2 second tolerance for test execution)
        assert before - 1 <= payload.iat <= after + 2, (
            f"Token issued-at {payload.iat} is outside expected range [{before - 1}, {after + 2}]"
        )
    
    @given(user_data=valid_user_data_strategy())
    @settings(max_examples=50, deadline=None)
    def test_property_token_with_special_characters_in_name(self, user_data):
        """
        Property: Tokens with special characters in user names verify successfully.
        
        **Validates: Requirements 48.3**
        
        For any valid user data (including special characters):
        1. Generate a token
        2. Verify the token
        3. Assert verification succeeds with exact name preservation
        
        This ensures proper handling of unicode and special characters.
        """
        user_id = user_data['user_id']
        email = user_data['email']
        # Use name with potential special characters from strategy
        name = user_data['name']
        
        # Generate token
        token = create_access_token(user_id, email, name)
        
        # Verify token
        payload = verify_token(token, expected_type="access")
        
        # Assert name is preserved exactly
        assert payload.name == name, f"Name not preserved: '{payload.name}' != '{name}'"


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
